### ISSUE TITLE
how to make this work in windows ?

### ISSUE THREAD

**Issue by fireheart2008** [romanwarlock/thumbnails#1]
using ffmpeg version: 2022-05-26 [all 3 files in c:/windows]
using the code, in command prompt
"D:\Downloads\Compressed\thumbnails-master\thumbgen.sh" 3 14 1920 video.mp4
a window pops up 'how do you want to open this file'

win 10 Version 21H2 (OS Build 19044.1706)

**Comment by fireheart2008** [comment]
even after using cmder bash environment  

pcc@ww /d/Downloads/Compressed/thumbnails-master
"D:\Downloads\Compressed\thumbnails-master\thumbgen.sh" 3 14 1920 video.mp4
D:\Downloads\Compressed\thumbnails-master\thumbgen.sh: line 45: bc: command not found
ffmpeg version 2022-05-26-git-0dcbe1c1aa-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.3.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 25.100 / 57. 25.100
  libavcodec     59. 32.100 / 59. 32.100
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 39.100 /  8. 39.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[image2 @ 0000016f6bb25080] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
/tmp/thumbnails-7024/*.jpeg: Function not implemented
D:\Downloads\Compressed\thumbnails-master\thumbgen.sh: line 78: bc: command not found
ffmpeg version 2022-05-26-git-0dcbe1c1aa-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.3.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 25.100 / 57. 25.100
  libavcodec     59. 32.100 / 59. 32.100
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 39.100 /  8. 39.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
C:/Users/pcc/AppData/Local/Temp/thumbnails-7024/output.jpg: No such file or directory
D:\Downloads\Compressed\thumbnails-master\thumbgen.sh: line 80: bc: command not found
ffmpeg version 2022-05-26-git-0dcbe1c1aa-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.3.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 25.100 / 57. 25.100
  libavcodec     59. 32.100 / 59. 32.100
  libavformat    59. 24.100 / 59. 24.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 39.100 /  8. 39.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
[color @ 00000234778f7c40] Unable to parse option value "1920x" as image size
[color @ 00000234778f7c40] Error setting option size to value 1920x.
[Parsed_color_0 @ 00000234778f7700] Error applying options to the filter.
[lavfi @ 00000234778f5140] Error initializing filter 'color' with args 'white:1920x'
color=white:1920x: Invalid argument
pcc@ww /d/Downloads/Compressed/thumbnails-master

**Comment by romanwarlock** [comment]
I see that **bc command is not found** - it is command line calculator in Linux, which is used to obtain calculate times and jpgs dimensions

So explore **how to add bc to windows**
Maybe https://stackoverflow.com/questions/55141267/how-to-install-and-where-to-install-bash-bc-on-windows could help
I don´t know. 
also keep in mind that script uses awk which is built-in Linux
So explore **how to add awk to windows**
- Explore the ways **how to run bash script in Windows** 
- Install Linux and install ffmpeg for Linux
- Use a virtual machine with Linux and ffmpeg

**Comment by romanwarlock** [comment]
Try new version where:

+ bc dependence has been REMOVED - awk is used for calculations, since
D:\Downloads\Compressed\thumbnails-master\thumbgen.sh: line 80: bc: command not found

+ ImageMagick dependence has been REMOVED - ffmpeg is used to work with jpg-files

**Comment by romanwarlock** [comment]
Try new version where:

bc dependence has been REMOVED - awk is used for calculations, since
D:\Downloads\Compressed\thumbnails-master\thumbgen.sh: line 80: bc: command not found

ImageMagick dependence has been REMOVED - ffmpeg is used to work with jpg-files
